openapi: 3.0.3
info:
  title: 'Laravel API Documentation'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
tags:
  -
    name: Endpoints
    description: ''
paths:
  /api/product:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: success
                  message: 'Products fetched Successfully'
                  code: 200
                  data:
                    data: []
                    links:
                      first: 'http://localhost/api/product?page=1'
                      last: 'http://localhost/api/product?page=1'
                      prev: null
                      next: null
                    meta:
                      current_page: 1
                      from: null
                      last_page: 1
                      links:
                        -
                          url: null
                          label: '&laquo; Previous'
                          active: false
                        -
                          url: 'http://localhost/api/product?page=1'
                          label: '1'
                          active: true
                        -
                          url: null
                          label: 'Next &raquo;'
                          active: false
                      path: 'http://localhost/api/product'
                      per_page: 10
                      to: null
                      total: 0
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: 'Products fetched Successfully'
                  code:
                    type: integer
                    example: 200
                  data:
                    type: object
                    properties:
                      data:
                        type: array
                        example: []
                      links:
                        type: object
                        properties:
                          first:
                            type: string
                            example: 'http://localhost/api/product?page=1'
                          last:
                            type: string
                            example: 'http://localhost/api/product?page=1'
                          prev:
                            type: string
                            example: null
                          next:
                            type: string
                            example: null
                      meta:
                        type: object
                        properties:
                          current_page:
                            type: integer
                            example: 1
                          from:
                            type: string
                            example: null
                          last_page:
                            type: integer
                            example: 1
                          links:
                            type: array
                            example:
                              -
                                url: null
                                label: '&laquo; Previous'
                                active: false
                              -
                                url: 'http://localhost/api/product?page=1'
                                label: '1'
                                active: true
                              -
                                url: null
                                label: 'Next &raquo;'
                                active: false
                            items:
                              type: object
                              properties:
                                url:
                                  type: string
                                  example: null
                                label:
                                  type: string
                                  example: '&laquo; Previous'
                                active:
                                  type: boolean
                                  example: false
                          path:
                            type: string
                            example: 'http://localhost/api/product'
                          per_page:
                            type: integer
                            example: 10
                          to:
                            type: string
                            example: null
                          total:
                            type: integer
                            example: 0
      tags:
        - Endpoints
      security: []
    post:
      summary: 'Store a newly created resource in storage.'
      operationId: storeANewlyCreatedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'The name of the product.'
                  example: Laptop
                  nullable: false
                category:
                  type: string
                  description: 'The category of the product.'
                  example: Electronics
                  nullable: false
                status:
                  type: boolean
                  description: 'Availability status of the product (true for available, false for unavailable).'
                  example: false
                  nullable: false
              required:
                - name
                - category
      security: []
  '/api/product/{id}':
    get:
      summary: ''
      operationId: getApiProductId
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'No query results for model [App\Models\Product].'
                properties:
                  message:
                    type: string
                    example: 'No query results for model [App\Models\Product].'
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the product.'
        example: 17
        required: true
        schema:
          type: integer
